operationalActivity: 
  codes:
    1: CMNF
    2: UDA PHASE 2
    3: MERCH IN TPI INCLUSION TABLE
    4: UDA PHASE 3
    5: JCB PAPER MERCHANT
    6: QUALIFIED SALE MERCHANT
    7: ACCOUNT SERVICED BY VANTIV (RMO)
    8: CARD PRESENT CID PROGRAM
    11: ARIBAPAY MERCHANT
    12: PROXY INSTRUMENT PROVIDERS (PIP)
    13: PAYMENT SERVICES PROVIDERS (PSP)
    14: UNSUSTAINABLE MERCHANT
    15: COLLUSIVE MERCHANT PROGRAM
    16: FRAUD MERCHANT PROGRAM
    17: EXCESSIVE FRAUD PROGRAM
    18: FULL CHIP
    19: PARTIAL CHIP
    21: DN RETAINED MERCHANT
    22: ORPHAN MERCHANT
    23: COMMERCIAL PAYMENTS MERCHANT
    24: INCLUDE FED TIN EDTI <rel 18.1>
    25: DEBT REPAYMENT <rel 18.1>
    5050: INTERNATIONAL THIRD PARTY
    5072: MP SPECIAL HANDLING - 8003477560
    5102: INTERNAL ACCOUNT
    5111: (NET) INTERNET MERCHANT
    5151: CUSTOM MOBILE REPORTING
    5152: CUSTOM MOBILE COMPANION REPORTING
    5154: CUSTOM MOBILE GROSS REPORTING
    5155: CUSTOM MOBILE NET REPORTING
    5500: GOVERNMENT SURCHARGE ACCT - IRQ USE ONLY
    5501: EXCLUSIVE ACCOUNTS - IRQ USE ONLY
    5504: DEBIT PREFERRED ACCOUNTS - IRQ USE ONLY
    5505: EXCLUSIVE AND PREFERRED - IRQ USE ONLY